const phraseDictionary = {
  en: {
    'how are you': 'na.a namengama',
    'i am fine': 'ang.a namengava',
    'what is your name': 'nang bimung maia',
    'i shall come with you': 'ang.a nangming reangen',
    'do you love me': 'na.a angna kasa.a ma',
    'yes i love you': 'hoe, ang.a nangna kasa.a',
    'can you give me your pen': 'na.a nang pen ko on.a mangenma',
    'yes of course': 'hoe mangenva',
    'he is eating an apple': 'bia apple cha.enga',
    'he ate an apple': 'bia apple cha.aha',
    'i saw the film last week': 'ang.a ia film ko nia mija antio',
    'she came by bus yesterday': 'bia bus o raba.a mijalo',
    'they went to the mosque': 'bisong olakiramchi re.anga',
    'he slept the whole night': 'bia walgimik tua',
    'he wrote well in the examination': 'bia porikka namen se.ataha',
    'he has eaten': 'bia chamanjok',
    'he had eaten': 'bia chaman.aha',
    'he had gone': 'bia reang.aha',
    'he had come': 'bia raba.aha',
    'he will eat': 'bia chagen',
    'he will go': 'bia reangen',
    'he will come': 'bia rebagen',
    'where did you come from': 'na.a banoni reba.a',
    'where did you sleep': 'na.a bano tusia',
    'where should i go': 'ang.ara batchi reangbo',
    'whom should i contact': 'ang.ar sako contact khagen',
    'is it a book': 'uara kitab ma',
    'is it the answer': 'iara aganchakani ma',
    'will you come with me': 'na.ara ang.ming rebagenma',
    'can you lift the box': 'na.a box ko dena mangenma',
    'can you write the exam': 'na.a porikka sena mangenma',
    'did you have lunch': 'na.a mi chajokma',
    'why did you come': 'na.a maina reba.a',
    'why did you sleep': 'na.a maina tusia',
    'how did you come': 'na.a maidake reba.a',
    'how did you sleep': 'na.a maidake tusia',
    'how did you drive': 'na.a maidake sal.a',
    'how did you write': 'na.a maidake se.a',
  },
  hi: {
    'आप कैसे हैं': 'na.a namengama',
    'मैं ठीक हूँ': 'ang.a namengava',
    'आपका नाम क्या है': 'nang bimung maia',
    'मैं आपके साथ आऊंगा': 'ang.a nangming reangen',
    'क्या आप मुझसे प्यार करते हैं': 'na.a angna kasa.a ma',
    'हाँ, मैं तुमसे प्यार करता हूँ': 'hoe, ang.a nangna kasa.a',
    'क्या आप मुझे अपनी कलम दे सकते हैं': 'na.a nang pen ko on.a mangenma',
    'जी, निश्चित रूप से': 'hoe mangenva',
    'वह एक सेब खा रहा है': 'bia apple cha.enga',
    'वह एक सेब खा गया': 'bia apple cha.aha',
    'मैंने पिछले हफ्ते फिल्म देखी': 'ang.a ia film ko nia mija antio',
    'वह कल बस से आई': 'bia bus o raba.a mijalo',
    'वे मस्जिद गए': 'bisong olakiramchi re.anga',
    'वह पूरी रात सोया': 'bia walgimik tua',
    'वह परीक्षा में अच्छी लिख गया': 'bia porikka namen se.ataha',
    'वह खा गया है': 'bia chamanjok',
    'वह खा चुका था': 'bia chaman.aha',
    'वह जा चुका था': 'bia reang.aha',
    'वह आ चुका था': 'bia raba.aha',
    'वह खाएगा': 'bia chagen',
    'वह जाएगा': 'bia reangen',
    'वह आएगा': 'bia rebagen',
    'आप कहाँ से आए': 'na.a banoni reba.a',
    'आप कहाँ सोए': 'na.a bano tusia',
    'मुझे कहाँ जाना चाहिए': 'ang.ara batchi reangbo',
    'मुझे किससे संपर्क करना चाहिए': 'ang.ar sako contact khagen',
    'क्या यह एक किताब है': 'uara kitab ma',
    'क्या यह उत्तर है': 'iara aganchakani ma',
    'क्या आप मेरे साथ आएंगे': 'na.ara ang.ming rebagenma',
    'क्या आप बॉक्स उठा सकते हैं': 'na.a box ko dena mangenma',
    'क्या आप परीक्षा लिख सकते हैं': 'na.a porikka sena mangenma',
    'क्या आपने दोपहर का भोजन किया': 'na.a mi chajokma',
    'आप क्यों आए': 'na.a maina reba.a',
    'आप क्यों सोए': 'na.a maina tusia',
    'आप कैसे आए': 'na.a maidake reba.a',
    'आप कैसे सोए': 'na.a maidake tusia',
    'आप कैसे चलाते हैं': 'na.a maidake sal.a',
    'आपने कैसे लिखा': 'na.a maidake se.a',
  },
  grt: {
    'na.a namengama': 'how are you',
    'ang.a namengava': 'i am fine',
    'nang bimung maia': 'what is your name',
    'ang.a nangming reangen': 'i shall come with you',
    'na.a angna kasa.a ma': 'do you love me',
    'hoe, ang.a nangna kasa.a': 'yes i love you',
    'na.a nang pen ko on.a mangenma': 'can you give me your pen',
    'hoe mangenva': 'yes of course',
    'bia apple cha.enga': 'he is eating an apple',
    'bia apple cha.aha': 'he ate an apple',
    'ang.a ia film ko nia mija antio': 'i saw the film last week',
    'bia bus o raba.a mijalo': 'she came by bus yesterday',
    'bisong olakiramchi re.anga': 'they went to the mosque',
    'bia walgimik tua': 'he slept the whole night',
    'bia porikka namen se.ataha': 'he wrote well in the examination',
    'bia chamanjok': 'he has eaten',
    'bia chaman.aha': 'he had eaten',
    'bia reang.aha': 'he had gone',
    'bia raba.aha': 'he had come',
    'bia chagen': 'he will eat',
    'bia reangen': 'he will go',
    'bia rebagen': 'he will come',
    'na.a banoni reba.a': 'where did you come from',
    'na.a bano tusia': 'where did you sleep',
    'ang.ara batchi reangbo': 'where should i go',
    'ang.ar sako contact khagen': 'whom should i contact',
    'uara kitab ma': 'is it a book',
    'iara aganchakani ma': 'is it the answer',
    'na.ara ang.ming rebagenma': 'will you come with me',
    'na.a box ko dena mangenma': 'can you lift the box',
    'na.a porikka sena mangenma': 'can you write the exam',
    'na.a mi chajokma': 'did you have lunch',
    'na.a maina reba.a': 'why did you come',
    'na.a maina tusia': 'why did you sleep',
    'na.a maidake reba.a': 'how did you come',
    'na.a maidake tusia': 'how did you sleep',
    'na.a maidake sal.a': 'how did you drive',
    'na.a maidake se.a': 'how did you write',
  },
};

const dictionaries = {
  en: {
    i: 'ang.a',
    he: 'ua',
    she: 'bia',
    you: 'na.a',
    it: 'ia',
    this: 'ia',
    that: 'haiwa',
    come: 'reba',
    came: 'reba.aha',
    open: 'khulibo',
    opened: 'khulia.a',
    sit: 'asongbo',
    walk: 'roranbo',
    eat: 'chabo',
    drink: 'ringbo',
    win: 'am.a',
    go: 'reangbo',
    run: 'katbo',
    sleep: 'tua',
    slept: 'tusia',
    write: 'se.a',
    wrote: 'sea',
    pay: 'gama',
    bring: 'raba.a',
    drive: 'sal.a',
    name: 'bimung',
    your: 'nangni',
    what: 'maia',
    why: 'maina',
    how: 'maidake',
    where: 'bano',
    which: 'badia',
    whom: 'sako',
    when: 'mijal',
    who: 'saka',
    yes: 'hoe',
    no: 'na',
    love: 'kasa.a',
    book: 'kitab',
    answer: 'aganchakani',
    pen: 'pen',
    box: 'box',
    exam: 'porikka',
    lunch: 'mi',
    bus: 'bus',
    mosque: 'olakiramchi',
    night: 'walgi',
    film: 'film',
    week: 'antio',
    school: 'skul',
    teacher: 'skulchi',
    student: 'skulchi',
    house: 'deng',
    home: 'deng',
    water: 'rinda',
    food: 'kimang',
    friend: 'dawa',
    child: 'chika',
    good: 'tang',
    morning: 'amang',
    thank: 'ang',
    thanks: 'ang',
    hello: 'hola',
    please: 'angchi',
    great: 'tang',
    beautiful: 'tang',
    big: 'fula',
    small: 'jiling',
    market: 'market',
    road: 'road',
    village: 'dingja',
    father: 'papa',
    mother: 'mama',
    brother: 'beng',
    sister: 'seng',
    son: 'chika',
    daughter: 'chika',
    man: 'misa',
    woman: 'seng',
    boy: 'chika',
    girl: 'chika',
    dog: 'kuchi',
    cat: 'meo',
    cow: 'misi',
    horse: 'gora',
    rice: 'chak',
    bread: 'roti',
    milk: 'dubi',
    tea: 'cha',
    coffee: 'kofi',
    money: 'gama',
    time: 'sam',
    day: 'sal',
    month: 'sal',
    year: 'sal',
    work: 'kam',
    job: 'kam',
    play: 'chik',
    game: 'chik',
    read: 'por.a',
    learn: 'por.a',
    speak: 'katchi',
    talk: 'katchi',
    see: 'nia',
    look: 'nia',
    hear: 'katchi',
    listen: 'katchi',
    one: 'sa',
    two: 'gni',
    three: 'gitam',
    four: 'bram',
    five: 'skai',
    six: 'dokkai',
    seven: 'sni',
    eight: 'chet',
    nine: 'sku',
    ten: 'chi',
  },
  hi: {
    'मैं': 'ang.a',
    'वह': 'ua',
    'आप': 'na.a',
    'यह': 'ia',
    'आओ': 'reba',
    'आया': 'reba.aha',
    'खोलो': 'khulibo',
    'खुला': 'khulia.a',
    'बैठो': 'asongbo',
    'चलो': 'roranbo',
    'खाओ': 'chabo',
    'पीओ': 'ringbo',
    'जीतो': 'am.a',
    'जाओ': 'reangbo',
    'दौड़ो': 'katbo',
    'सोओ': 'tua',
    'सोया': 'tusia',
    'लिखो': 'se.a',
    'लिखा': 'sea',
    'दो': 'gama',
    'लाओ': 'raba.a',
    'चलाओ': 'sal.a',
    'नाम': 'bimung',
    'आपका': 'nangni',
    'क्या': 'maia',
    'क्यों': 'maina',
    'कैसे': 'maidake',
    'कहाँ': 'bano',
    'कौन': 'saka',
    'कौन सा': 'badia',
    'किसको': 'sako',
    'कब': 'mijal',
    'हाँ': 'hoe',
    'नहीं': 'na',
    'प्यार': 'kasa.a',
    'किताब': 'kitab',
    'उत्तर': 'aganchakani',
    'कलम': 'pen',
    'बॉक्स': 'box',
    'परीक्षा': 'porikka',
    'दोपहर': 'mi',
    'बस': 'bus',
    'मस्जिद': 'olakiramchi',
    'रात': 'walgi',
    'फिल्म': 'film',
    'हफ्ता': 'antio',
    'स्कूल': 'skul',
    'टीचर': 'skulchi',
    'स्टूडेंट': 'skulchi',
    'घर': 'deng',
    'पानी': 'rinda',
    'खाना': 'kimang',
    'दोस्त': 'dawa',
    'बच्चा': 'chika',
    'अच्छा': 'tang',
    'सुबह': 'amang',
    'धन्यवाद': 'ang',
    'हैलो': 'hola',
    'कृपया': 'angchi',
    'बड़ा': 'fula',
    'छोटा': 'jiling',
    'बाजार': 'market',
    'सड़क': 'road',
    'गाँव': 'dingja',
    'पिता': 'papa',
    'माता': 'mama',
    'भाई': 'beng',
    'बहन': 'seng',
    'बेटा': 'chika',
    'बेटी': 'chika',
    'आदमी': 'misa',
    'औरत': 'seng',
    'लड़का': 'chika',
    'लड़की': 'chika',
    'कुत्ता': 'kuchi',
    'बिल्ली': 'meo',
    'गाय': 'misi',
    'घोड़ा': 'gora',
    'चावल': 'chak',
    'रोटी': 'roti',
    'दूध': 'dubi',
    'चाय': 'cha',
    'कॉफी': 'kofi',
    'पैसे': 'gama',
    'समय': 'sam',
    'दिन': 'sal',
    'महीना': 'sal',
    'साल': 'sal',
    'काम': 'kam',
    'खेल': 'chik',
    'पढ़ो': 'por.a',
    'सीखो': 'por.a',
    'बोलो': 'katchi',
    'देखो': 'nia',
    'सुनो': 'katchi',
    'एक': 'sa',
    'दो': 'gni',
    'तीन': 'gitam',
    'चार': 'bram',
    'पाँच': 'skai',
    'छह': 'dokkai',
    'सात': 'sni',
    'आठ': 'chet',
    'नौ': 'sku',
    'दस': 'chi',
  },
  grtToEn: {
    'ang.a': 'I',
    'ua': 'he',
    'bia': 'she',
    'na.a': 'you',
    'ia': 'it',
    'haiwa': 'that',
    'reba': 'come',
    'reba.aha': 'came',
    'khulibo': 'open',
    'khulia.a': 'opened',
    'asongbo': 'sit',
    'roranbo': 'walk',
    'chabo': 'eat',
    'ringbo': 'drink',
    'am.a': 'win',
    'reangbo': 'go',
    'katbo': 'run',
    'tua': 'sleep',
    'tusia': 'slept',
    'se.a': 'write',
    'sea': 'wrote',
    'gama': 'pay',
    'raba.a': 'bring',
    'sal.a': 'drive',
    'bimung': 'name',
    'nangni': 'your',
    'maia': 'what',
    'maina': 'why',
    'maidake': 'how',
    'bano': 'where',
    'badia': 'which',
    'sako': 'whom',
    'mijal': 'when',
    'saka': 'who',
    'hoe': 'yes',
    'kasa.a': 'love',
    'kitab': 'book',
    'aganchakani': 'answer',
    'pen': 'pen',
    'box': 'box',
    'porikka': 'exam',
    'mi': 'lunch',
    'bus': 'bus',
    'olakiramchi': 'mosque',
    'walgi': 'night',
    'film': 'film',
    'skul': 'school',
    'skulchi': 'teacher',
    'deng': 'house',
    'rinda': 'water',
    'kimang': 'food',
    'dawa': 'friend',
    'chika': 'child',
    'tang': 'good',
    'amang': 'morning',
    'ang': 'thank',
    'hola': 'hello',
    'angchi': 'please',
    'fula': 'big',
    'jiling': 'small',
    'market': 'market',
    'road': 'road',
    'dingja': 'village',
    'papa': 'father',
    'mama': 'mother',
    'beng': 'brother',
    'seng': 'sister',
    'misa': 'man',
    'kuchi': 'dog',
    'meo': 'cat',
    'misi': 'cow',
    'gora': 'horse',
    'chak': 'rice',
    'roti': 'bread',
    'dubi': 'milk',
    'cha': 'tea',
    'kofi': 'coffee',
    'sam': 'time',
    'sal': 'day',
    'kam': 'work',
    'chik': 'play',
    'por.a': 'read',
    'katchi': 'speak',
    'nia': 'see',
    'sa': 'one',
    'gni': 'two',
    'gitam': 'three',
    'bram': 'four',
    'skai': 'five',
    'dokkai': 'six',
    'sni': 'seven',
    'chet': 'eight',
    'sku': 'nine',
    'chi': 'ten',
  },
  grtToHi: {
    'ang.a': 'मैं',
    'ua': 'वह',
    'bia': 'वह',
    'na.a': 'आप',
    'ia': 'यह',
    'haiwa': 'वह',
    'reba': 'आओ',
    'reba.aha': 'आया',
    'khulibo': 'खोलो',
    'khulia.a': 'खुला',
    'asongbo': 'बैठो',
    'roranbo': 'चलो',
    'chabo': 'खाओ',
    'ringbo': 'पीओ',
    'am.a': 'जीतो',
    'reangbo': 'जाओ',
    'katbo': 'दौड़ो',
    'tua': 'सोओ',
    'tusia': 'सोया',
    'se.a': 'लिखो',
    'sea': 'लिखा',
    'gama': 'दो',
    'raba.a': 'लाओ',
    'sal.a': 'चलाओ',
    'bimung': 'नाम',
    'nangni': 'आपका',
    'maia': 'क्या',
    'maina': 'क्यों',
    'maidake': 'कैसे',
    'bano': 'कहाँ',
    'badia': 'कौन',
    'sako': 'किसको',
    'mijal': 'कब',
    'saka': 'कौन',
    'hoe': 'हाँ',
    'kasa.a': 'प्यार',
    'kitab': 'किताब',
    'aganchakani': 'उत्तर',
    'pen': 'कलम',
    'box': 'बॉक्स',
    'porikka': 'परीक्षा',
    'mi': 'दोपहर',
    'bus': 'बस',
    'olakiramchi': 'मस्जिद',
    'walgi': 'रात',
    'film': 'फिल्म',
    'skul': 'स्कूल',
    'skulchi': 'टीचर',
    'deng': 'घर',
    'rinda': 'पानी',
    'kimang': 'खाना',
    'dawa': 'दोस्त',
    'chika': 'बच्चा',
    'tang': 'अच्छा',
    'amang': 'सुबह',
    'ang': 'धन्यवाद',
    'hola': 'हैलो',
    'angchi': 'कृपया',
    'fula': 'बड़ा',
    'jiling': 'छोटा',
    'market': 'बाजार',
    'road': 'सड़क',
    'dingja': 'गाँव',
    'papa': 'पिता',
    'mama': 'माता',
    'beng': 'भाई',
    'seng': 'बहन',
    'misa': 'आदमी',
    'kuchi': 'कुत्ता',
    'meo': 'बिल्ली',
    'misi': 'गाय',
    'gora': 'घोड़ा',
    'chak': 'चावल',
    'roti': 'रोटी',
    'dubi': 'दूध',
    'cha': 'चाय',
    'kofi': 'कॉफी',
    'sam': 'समय',
    'sal': 'दिन',
    'kam': 'काम',
    'chik': 'खेल',
    'por.a': 'पढ़ो',
    'katchi': 'बोलो',
    'nia': 'देखो',
    'sa': 'एक',
    'gni': 'दो',
    'gitam': 'तीन',
    'bram': 'चार',
    'skai': 'पाँच',
    'dokkai': 'छह',
    'sni': 'सात',
    'chet': 'आठ',
    'sku': 'नौ',
    'chi': 'दस',
  },
};


const translationPatterns = [
  {
    from: 'en',
    to: 'grt',
    regex: /^where is (?:the )?(.+)$/,
    handler: (match) => `${translateWordByWord(match[1], dictionaries.en)} fingga`,
  },
  {
    from: 'en',
    to: 'grt',
    regex: /^i want (.+)$/,
    handler: (match) => `ang.a se ${translateWordByWord(match[1], dictionaries.en)}`,
  },
  {
    from: 'en',
    to: 'grt',
    regex: /^do you have (.+)$/,
    handler: (match) => `na.a ${translateWordByWord(match[1], dictionaries.en)} da`,
  },
  {
    from: 'en',
    to: 'grt',
    regex: /^let us go$/,
    handler: () => 'ning reangbo',
  },
  {
    from: 'hi',
    to: 'grt',
    regex: /^(.+) कहाँ है$/,
    handler: (match) => `${translateWordByWord(match[1], dictionaries.hi)} fingga`,
  },
  {
    from: 'hi',
    to: 'grt',
    regex: /^मुझे (.+) चाहिए$/,
    handler: (match) => `ang.a se ${translateWordByWord(match[1], dictionaries.hi)}`,
  },
  {
    from: 'grt',
    to: 'en',
    regex: /^(.+) fingga$/,
    handler: (match) => `where is ${translateWordByWord(match[1], dictionaries.grtToEn)}`,
  },
  {
    from: 'grt',
    to: 'hi',
    regex: /^(.+) fingga$/,
    handler: (match) => `${translateWordByWord(match[1], dictionaries.grtToHi)} कहाँ है`,
  },
];

function normalizeText(text) {
  return text
    .trim()
    .toLowerCase()
    .replace(/[?!,]+/g, '')
    .replace(/\s+/g, ' ');
}

function translatePhrase(text, from) {
  const normalized = normalizeText(text);
  if (phraseDictionary[from] && phraseDictionary[from][normalized]) {
    return phraseDictionary[from][normalized];
  }
  return null;
}

function translatePattern(text, from, to) {
  const normalized = normalizeText(text);
  const pattern = translationPatterns.find((item) => item.from === from && item.to === to && item.regex.test(normalized));
  if (!pattern) return null;
  const match = normalized.match(pattern.regex);
  return match ? pattern.handler(match) : null;
}

function translateWordByWord(text, dictionary) {
  const normalized = normalizeText(text);
  return normalized
    .split(' ')
    .map((word) => dictionary[word] ?? word)
    .join(' ')
    .replace(/\s+/g, ' ')
    .trim();
}

export function detectLanguage(text) {
  const normalized = normalizeText(text);
  if (/[ऀ-ॿ]/.test(text)) {
    return 'hi';
  }

  const words = normalized.split(' ').filter(Boolean);
  const counts = {
    grt: words.filter((word) => dictionaries.grtToEn[word] || dictionaries.grtToHi[word]).length,
    hi: words.filter((word) => dictionaries.hi[word]).length,
    en: words.filter((word) => dictionaries.en[word]).length,
  };

  if (counts.grt >= Math.max(counts.en, counts.hi) && counts.grt > 0) {
    return 'grt';
  }
  if (counts.hi > counts.en) {
    return 'hi';
  }
  return 'en';
}

export default function translateText(text, from, to) {
  if (!text || !text.trim()) return '';
  if (from === to) return text;

  const normalized = normalizeText(text);
  const phrase = translatePhrase(normalized, from, to);
  if (phrase) return phrase;

  const pattern = translatePattern(normalized, from, to);
  if (pattern) return pattern;

  if (from === 'en' && to === 'grt') {
    return translateWordByWord(normalized, dictionaries.en);
  }

  if (from === 'hi' && to === 'grt') {
    return translateWordByWord(normalized, dictionaries.hi);
  }

  if (from === 'grt' && to === 'en') {
    return translateWordByWord(normalized, dictionaries.grtToEn);
  }

  if (from === 'grt' && to === 'hi') {
    return translateWordByWord(normalized, dictionaries.grtToHi);
  }

  if (from !== 'grt' && to !== 'grt') {
    const intermediate = translateText(text, from, 'grt');
    return translateText(intermediate, 'grt', to);
  }

  return 'Translation unavailable for this language pair.';
}
